[package]
name = "hello-rust-bubble-sort"
version = "0.1.0"
edition = "2021"
authors = ["Xiaobo Tian <peterwillcn@gmail.com>"]

[dependencies]
structopt = { version = "0.3", default-features = false }
